maptiler/maptiler-sdk-js

package.json

Hi @jonathanlurie 
following up on our conversation with my last issue regarding type discoverability,
I did some research and found some mistakes we've made regarding the issue.
Vite's default module resolution is set to "bundler" which comes with typescript 5.0, [source](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler).
it is not legacy and should be the way forward.
some other maintainers have encountered this issue, and [solved it](https://github.com/nolimits4web/swiper/pull/6626)
I have attempted the same solution from source and it worked like a charm.
in regard to backwards compatibility, I have, of course, left everything else like it was although it seems to introduce some duplication.

fix type declaration with "bundler"  moduleRes

---

CHANGELOG.md
demos/readyevent.html
package-lock.json
package.json
readme.md
src/Map.ts
src/index.ts

The major goal for this version is to update the SDK with the MapTiler Client library v1.8.0. This version brings the lookup/computation of the elevation as well as the math module.
A second objective was to expose all the types that are used as function options, in particular regarding the geocoding. Now, all the TS type definition are properly exposed/routed from the Client lib.
Extra addition: the `ready` event and on `.onReadyAsync()` Map method. Those occur after `load`, when all the controls managed by the Map constructor are dealt with, including those with an asynchronous logic. As a result, the `ready` event is safer to wait for than the `load` because it guaranties that the placement of controls added at constructor time is finished and that new controls can be added.
Lastly, …

Update with client lib v1.8.0 to bring elevation

---

CHANGELOG.md
src/Map.ts
src/caching.ts
src/config.ts
src/tools.ts

RD-235
Add client-side caching using browser Cache API to reduce network load for repeated sessions.
- `transformRequest` + `addProtocol` used to hook into the maplibre
- The cache is reused even between different map sessions (`mtsid` and `key` are ignored).
- Soft limit of 1000 items in the cache, checked periodically, oldest items are then removed.
- Special handling for TileJSON to actually propagate `Last-Modified` to the tile requests (so that the cache is not reused when outdated).
Tested locally

Client-side caching for fonts and tiles

---

src/caching.ts

See #78 for details. Bundled code contained an import from maplibre-gl.
```ts
import maplibregl, {addProtocol as addProtocol$1} from 'maplibre-gl';
```
Rather than importing from maplibre-gl _again_, the functions can be imported from `index.ts` where they are re-exported anyway, preventing the bundler from importing `addProtocol` as named import and renaming it.
In `caching.ts` I tweaked the import.
The resulting bundle imports the default import from maplibre-gl only.

Fixing bundled imports

---

CHANGELOG.md
package.json
src/index.ts

[RD-249](https://maptiler.atlassian.net/browse/RD-249)
[RD-249]: https://maptiler.atlassian.net/browse/RD-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Version update related to #79

---

CHANGELOG.md
package-lock.json
package.json
src/Map.ts

[RD-252](https://maptiler.atlassian.net/browse/RD-252)
[RD-252]: https://maptiler.atlassian.net/browse/RD-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update attribution options

---

CHANGELOG.md
src/caching.ts

RD-254
Loading GeoJSON sources from api.maptiler.com is currently broken due to a bug in the client-side caching mechanism
More robust filtering. `ResourceType` was not enough, because the same value is actually used for TileJSONs and GeoJSONs.

Fix for the client-side caching breaking GeoJSON sources

---

CHANGELOG.md
package.json
src/Map.ts

[RD-255](https://maptiler.atlassian.net/browse/RD-255)
[RD-255]: https://maptiler.atlassian.net/browse/RD-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix attribution control bug

---

CHANGELOG.md
demos/simple.html
src/Map.ts
src/style/style_template.css
src/tools.ts

[RD-269](https://maptiler.atlassian.net/browse/RD-269)
Now showing a message in the map-hosting div as well as throw a more readable error:
(the grey part is just the style given to the map container div in this example)
[RD-269]: https://maptiler.atlassian.net/browse/RD-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Better handling of non-webgl2 support

---

CHANGELOG.md
package.json
src/Map.ts
src/tools.ts

[RD-287](https://maptiler.atlassian.net/browse/RD-287)
Since Maplibre v4 many callback logic has been replaced by Promises and for some reason, I forgot to update this one as part of SDK v2. This PR address that.
[RD-287]: https://maptiler.atlassian.net/browse/RD-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-287: RTL plugin no longer loads automatically 

---

CHANGELOG.md
package-lock.json
package.json
src/Map.ts
src/index.ts
src/tools.ts

[RD-292](https://maptiler.atlassian.net/browse/RD-292)
This PR addresses the type issue (https://github.com/maptiler/maptiler-sdk-js/issues/97) that caused some classes defined in Maplibre to not have their type visible, despite being usable (in JS).
[RD-292]: https://maptiler.atlassian.net/browse/RD-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Better type export

---

CHANGELOG.md
src/helpers/vectorlayerhelpers.ts

[RD-318](https://maptiler.atlassian.net/browse/RD-318)
[RD-318]: https://maptiler.atlassian.net/browse/RD-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-318: propagating the beforeId option on heatmap layer helper

---

CHANGELOG.md
package-lock.json
package.json
src/Map.ts
src/config.ts
src/index.ts
src/language.ts

[RD-315](https://maptiler.atlassian.net/browse/RD-315)
This is about updating the language list that is now sourced from the Client library (https://github.com/maptiler/maptiler-client-js/pull/42)
[RD-315]: https://maptiler.atlassian.net/browse/RD-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-315: sourcing the language list from the client library

---

CHANGELOG.md
package-lock.json
package.json

[RD-321](https://maptiler.atlassian.net/browse/RD-321)
[RD-321]: https://maptiler.atlassian.net/browse/RD-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-321: Update to Maplibre v4.7.0

---

CHANGELOG.md
readme.md
src/Map.ts

[RD-327](https://maptiler.atlassian.net/browse/RD-327)
Adding terrain animation events `terrainAnimationStart` and `terrainAnimationStop` as well as the Map method `.setTerrainAnimationDuration(d: number)`
[RD-327]: https://maptiler.atlassian.net/browse/RD-327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-327: add terrain animation events

---

CHANGELOG.md
readme.md
src/Map.ts
src/style/style_template.css
src/tools.ts

[RD-298](https://maptiler.atlassian.net/browse/RD-298)
[RD-298]: https://maptiler.atlassian.net/browse/RD-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-298: Add WebGL context loss warning message

---

CHANGELOG.md
package-lock.json
package.json

[RD-368](https://maptiler.atlassian.net/browse/RD-368)
[RD-368]: https://maptiler.atlassian.net/browse/RD-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-368 : Update maplibre v4.7.1

---

readme.md

This PR fixes various typos in the README.md file to improve documentation clarity and professionalism.
- "Instanciate" → "Instantiate"
- "addess" → "address"
- "generaly" → "generally"
- "begining" → "beginning"
- "amond" → "among"
- "ranin" → "ran in"
- "ressources" → "resources"
- "dynmicaly" → "dynamically"
- "The maps is" → "The map is"
- "polylons" → "polygons"
- Fixed duplicate "outlineWidth" property
- Various formatting and indentation improvements
- ✓ Verified all changes manually
- ✓ Confirmed markdown formatting remains intact
- ✓ Checked that code examples are properly formatted
- ✓ Ensured no unintended changes were introduced
Link to Devin run: https://preview.devin.ai/devin/5208a0d9083e4f3e8a8a14f10de0a1bd

Fix typos in README.md

---

CHANGELOG.md
package-lock.json
package.json
src/Map.ts
src/tools.ts
tsconfig.json

[RD-438](https://maptiler.atlassian.net/browse/RD-438)
The language switching is now working better and is more robust when there is advance styling or ramping
[RD-438]: https://maptiler.atlassian.net/browse/RD-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Language switching fixed

---

CHANGELOG.md
package-lock.json
package.json
src/MaptilerGeolocateControl.ts

[RD-447](https://maptiler.atlassian.net/browse/RD-447)
The method added (`_setErrorState`) is a direct port from Maplibre but with a small modification. Since the class MaptilerGeolocateControl inherits Maplibre's GeolocateControl then the local version of the method is being used instead.
[RD-447]: https://maptiler.atlassian.net/browse/RD-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Quiet error on geolocate control with Firefox

---

CHANGELOG.md
src/Map.ts
src/Telemetry.ts
src/config.ts
src/defaults.ts

[RD-452](https://maptiler.atlassian.net/browse/RD-452)  
[RD-454](https://maptiler.atlassian.net/browse/RD-454)  
[RD-455](https://maptiler.atlassian.net/browse/RD-455)
From each module, the Telemetry feature should be used as such:
```ts
import packagejson from "../package.json";
map.telemetry.registerModule(packagejson.name, packagejson.version);
```
[RD-452]: https://maptiler.atlassian.net/browse/RD-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-454]: https://maptiler.atlassian.net/browse/RD-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-455]: https://maptiler.atlassian.net/browse/RD-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding telemetry

---

readme.md

[RD-477](https://maptiler.atlassian.net/browse/RD-477)
The feature existed but there was no mention of it in the readme.
[RD-477]: https://maptiler.atlassian.net/browse/RD-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update readme with gpx and kml converter

---

demos/handling-webgl-errors.html
demos/sky_day_globe.html
demos/sky_night.html
demos/sky_night_globe.html
src/Map.ts
src/index.ts
src/tools.ts

What is the goal?
What changed, how and why?
How were changes tested?

RD-459_reimplement-handling-webgl-context-loss

---

package-lock.json
package.json
src/utils/MTAnimation/AnimationManager.ts
src/utils/MTAnimation/MTAnimation.ts
src/utils/MTAnimation/animation-helpers.ts
src/utils/MTAnimation/easing.ts
src/utils/MTAnimation/easings.d.ts
src/utils/MTAnimation/types.ts

To allow for easing functions to be applied between keyframes
- async loading of easing functions lib to avoid package bloat, defaults to linear.
- implement easing functions and alpha in update method.
- switch from using `Set` to using array in `AnimationManager` `update` method (more performant)
- removes superflous interface declaration for `MTAnimation` and inline documents methods.
Manually, tests will be in a later ticket
- ~[ ] I have added relevant info to the CHANGELOG.md~ N/A as we're merging to feature / epic branch, version bump and changelog entry will come when epic branch is merged

Rd776 add easing functions to animations

---

CHANGELOG.md
package-lock.json
package.json
src/Map.ts

To fix the reported issues below in addition to a bug where `ProjectionControl` would intermittently error, this was also observed when the `projectionControl` was loaded and then a subsequent call to `Map.setStyle` was made.
https://github.com/maptiler/maptiler-sdk-js/issues/175
https://github.com/maptiler/maptiler-sdk-js/issues/174
Method tests for existence of projection object before accessing a field (this type is incorrect in maplibre)
Manually tested.

RD858 `projection` is sometimes undefined

---

README.md

Named import is better practice as it will lead to smaller bundle size when used
Use named import in the Readme
Readme update
Not needed

Use named import in the Readme

---

demos/07-animated-routes.html
src/custom-layers/AnimatedRouteLayer.ts
src/utils/MaptilerAnimation/animation-helpers.ts
test/AnimatedRouteLayer/AnimatedRouteLayer.test.ts
test/MaptilerAnimation/MaptilerAnimation.test.ts
test/exports.test.ts
test/tsconfig.json
tsconfig.json

Better test coverage
- fix demos so that they use the correct enum for easing
- implement additional tests for AnimatedRouteLayer
- minor refactor
- add warning in exports.test regarding cjs module error
- code tidy-up
- add extended tsconfig for tests
Tests passing
- ~[ ] I have added relevant info to the CHANGELOG.md~ N/A until feature is merged to main.

Rd 787 animated route layer tests

---

CHANGELOG.md
eslint.config.mjs
package-lock.json
package.json
src/caching.ts

To fix [RD-902](https://maptiler.atlassian.net/browse/RD-902?atlOrigin=eyJpIjoiNGM2NGQxNzg0ZjEzNGJlMGI3M2Y1YTM3YTIyNjdkMDkiLCJwIjoiaiJ9)
Changes to use default import for maplibre-gl as it uses commonjs modules under the hood.
Manually Tested
[RD-902]: https://maptiler.atlassian.net/browse/RD-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-902 Fixes MapLibre direct import due to CJS issues

---

.github/workflows/npm-publish.yml
CHANGELOG.md
package-lock.json
package.json
tsconfig.json

To update tsconfig to prevent build failures in CI
- Updated tsconfig to prevent build failures in CI, and avoid linting the lint config
- Add github action to check if build passed before publishing to npm
Manually tested

Rd 902/remove eslint mjs from tsconfig

---

.github/workflows/npm-publish.yml

Remove duplicate tasks in the github npm publish action
in `.github/workflows/npm-publish.yml`, remove duplicate tasks in the github npm publish action
N/A
- ~[ ] I have added relevant info to the CHANGELOG.md~ N/A Does not change any public facing APIs nor build processes.

hotfix: remove duplicate commands from github publish action

---

CHANGELOG.md
package-lock.json
package.json
src/helpers/index.ts
src/index.ts

To export non-exported types
- helpers types were not exported correctly and so are now exported explicitly.
Manually

RD-685 Fix type exports

---

src/Map.ts
src/custom-layers/CubemapLayer/CubemapLayer.ts
src/custom-layers/CubemapLayer/loadCubemapTexture.ts
src/custom-layers/extractCustomLayerStyle.ts

To fix a bug where changes to style.json only partially applies changes in CubemapLayer
- add promises and callback to `loadCubemapTexture` to ensure onReady callback is only fired when all images are loaded
- add image.complete check to avoid non-firing of load event when image is cached.
- refactor logic that updates texture when styles are changed.
Manually

RD-901 Fix style.json changes not being reflected in CubemapLayer

---

CHANGELOG.md
src/Map.ts

Fixes [a bug](https://maptiler.atlassian.net/browse/RD-1025?atlOrigin=eyJpIjoiNzE2NDJiMjE2OWY4NDc0YThhMmUyMjhlMmQyNDBjODIiLCJwIjoiaiJ9) where calling `enableTerrain` directly after `flyTo` prevented the terrain from loading.
- eneableTerrain nows sets an event listener for `movend` event which fires when `flyTo` (or `moveTo`) is finished.
- better formatting of changelog.md
Manually

Rd 1025 flyto then terrain does not work

---

CHANGELOG.md
demos/src/01-simple.ts
package-lock.json
package.json
src/Map.ts
src/custom-layers/extractCustomLayerStyle.ts
src/custom-layers/index.ts

Fixes [216](https://github.com/maptiler/maptiler-sdk-js/issues/216)
- Add additional conditions to logging in `extractCustomLayerStyle`
- Updates API to stop typescript erroring when `map.setStyle` is called with a `StyleSpecificationWithMetaData` object.
- Unit tests
- Manually

Rd 1086 reduce logging output

---

demos/src/07-spacebox.ts
src/Map.ts
src/Telemetry.ts
src/custom-layers/CubemapLayer/CubemapLayer.ts
src/custom-layers/RadialGradientLayer/RadialGradientLayer.ts
src/custom-layers/extractCustomLayerStyle.ts
src/declarations.d.ts
vite.config-dev.ts
vite.config-es.ts
vite.config-test.ts
vite.config-umd.ts

Fixes [RD-1167](https://maptiler.atlassian.net/browse/RD-1167)
- process.env.NODE_ENV is not present in UMD bundle, so we leverage Vite to pass a custom define.
- better handling of space configs in constructor
- Unit tests
- Manually tested
[RD-1167]: https://maptiler.atlassian.net/browse/RD-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-1167 Space crashes in UMD when only a color is defined

---

CHANGELOG.md
README.md
demos/public/09-custom-controls-declarative.html
demos/public/10-custom-controls-programmatic.html
demos/public/index.html
demos/src/09-custom-controls-declarative.ts
demos/src/10-custom-controls-programmatic.ts
src/Map.ts
src/controls/MaptilerCustomControl.ts
src/controls/MaptilerExternalControl.ts
src/controls/MaptilerProjectionControl.ts
src/controls/MaptilerTerrainControl.ts
src/controls/index.ts
test/__snapshots__/exports.test.ts.snap
test/custom-control.test.ts
test/external-control.test.ts
vite.config-test.ts

Provide a way to add custom controls to map.
* `MaptilerCustomControl` class has been added that allows any element to become a map control, with shortcuts for click and map render event handlers.
* `customControls` map option that turns on auto-detection of custom control elements processed by `MaptilerExternalControl` class which provides some predefined click handlers too.
* Unit tests
* Manual tests

RD-509 Custom Controls

---

CHANGELOG.md
src/Map.ts

* Fix a bug
* Projection is not set in stylesheet when default projection is used, patched `getProjection()` method to detect that case and return the correct projection
* Manual tests

RD-532 fix map.getProjection() failing on default projection
