maptiler/maptiler-sdk-js

readme.md
Fix links to docs and fix typos #86  
Change links to docs
Fix typos
Locally
=> CU-452 fixes #86 fix typos and links

CHANGELOG.md, demos/simple.html, package-lock.json, package.json, src/tools.ts
[RD-277](https://maptiler.atlassian.net/browse/RD-277)
[RD-277]: https://maptiler.atlassian.net/browse/RD-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RD-277: Update maplibre to v4.4.0 and adjusted typing

src/Map.ts, src/caching.ts
[RD-270](https://maptiler.atlassian.net/browse/RD-270)
[RD-270]: https://maptiler.atlassian.net/browse/RD-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make sure the cache is running only if cache API is available

CHANGELOG.md, demos/sky_day.html, demos/sky_night.html, package-lock.json, package.json, src/MaptilerGeolocateControl.ts, src/Minimap.ts
[RD-289](https://maptiler.atlassian.net/browse/RD-289)
[RD-289]: https://maptiler.atlassian.net/browse/RD-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating to latest Maplibre

CHANGELOG.md, package-lock.json, package.json
[RD-313](https://maptiler.atlassian.net/browse/RD-313)
[RD-313]: https://maptiler.atlassian.net/browse/RD-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RD-302: Update Maplibre v4.6.0

CHANGELOG.md, src/index.ts
[RD-326](https://maptiler.atlassian.net/browse/RD-326)
[RD-326]: https://maptiler.atlassian.net/browse/RD-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RD-326: expose webgl support error

readme.md
[RD-362](https://maptiler.atlassian.net/browse/RD-362)
The issue was further discussed here https://github.com/maptiler/maptiler-sdk-js/issues/117
[RD-362]: https://maptiler.atlassian.net/browse/RD-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Addressing maplibre type issues

CHANGELOG.md, package-lock.json, package.json, src/Map.ts
[RD-402](https://maptiler.atlassian.net/browse/RD-402)
Relates to https://github.com/maptiler/maptiler-sdk-js/issues/127
[RD-402]: https://maptiler.atlassian.net/browse/RD-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix AJAXError import

.github/workflows/format-lint.yml, .github/workflows/npm-publish.yml, CHANGELOG.md
[RD-399](https://maptiler.atlassian.net/browse/RD-399)
[RD-399]: https://maptiler.atlassian.net/browse/RD-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Github action for beta version publishing on NPM

CHANGELOG.md, package-lock.json, package.json
[RD-476](https://maptiler.atlassian.net/browse/RD-476)
[RD-476]: https://maptiler.atlassian.net/browse/RD-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RD-476: update client library

README.md
Fix readme
Fixed readme
Reading readme
=> Remove info about animating projection change

README.md, src/config.ts
Add telemetry info to readme
Added telemetry info to readme
Read readme
=> readme_telemetry-info

.husky/pre-commit, package-lock.json, package.json
What is the goal?
What changed, how and why?
How were changes tested?
=> RD-639_pre-commit-hook

src/utils/MTAnimation/AnimationManager.ts, src/utils/MTAnimation/MTAnimation.ts, src/utils/MTAnimation/animation-helpers.ts, src/utils/MTAnimation/easing.ts, src/utils/MTAnimation/types.ts, src/utils/array.ts
To provide a util function that converts GeoJSON LineStrings, MultiPoints and Polygons (with proprty data) to keyframes objects usable in MTAnimation
See above
Manually tests, unit tests are incoming in a separate ticket.
=> RD772: implement GeoJSON to keyframes util function

CHANGELOG.md, README.md, package-lock.json, package.json
Update version of maptiler-client-js to the latest version.
Update version of maptiler-client-js to the latest version.
Manually tested
=> Upgrade to MapTiler client v2.3.0

CHANGELOG.md, package-lock.json, package.json
Version bump client-js to 2.3.1
Version bump client-js to 2.3.1
Manually Tested
=> Rd 881 version bump for client js

CHANGELOG.md, demos/05-transform-request.html, demos/06-handling-webgl-errors.html, package-lock.json, package.json
To update our maplibre dependency.
- Update our maplibre dependency.
- Fix some broken demos
manually tested
=> Rd 877 update maplibre

CHANGELOG.md
To update the changelog to include some additional info
The changelog, to include some additional info.
By checking the changelog.
=> RD-924 Update CHANGELOG.md

CHANGELOG.md, demos/src/02-sky-day.ts, demos/src/06-handling-webgl-errors.ts, demos/src/demo-utils.ts, package-lock.json, package.json, test/exports.test.ts, vite.config-dev.ts
To version bump the Maptiler SDK to the latest version
- Maptiler Version bump to 5.5.0
- Update broken / buggy demos
Tests run and manual testing
=> RD-957 Update MapLibre to latest version

package-lock.json, package.json
Version Bump package.json + package-lock.json to 3.5.0
Version Bump package.json + package-lock.json to 3.5.0
Manually
=> Version bump to 3.5.0

CHANGELOG.md, package-lock.json, package.json, src/Map.ts, src/custom-layers/CubemapLayer/CubemapLayer.ts, src/custom-layers/RadialGradientLayer/RadialGradientLayer.ts
Fix for [RD-1112](https://maptiler.atlassian.net/browse/RD-1112)
- Adds additional validation of spacebox and halo config
- Refactoring of logic in setStyle that inits / sets space and halo from style json
- Manually
- Unit tests passing.
[RD-1112]: https://maptiler.atlassian.net/browse/RD-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Rd 1112 projection change to mercator breaks style loading

README.md, demos/src/08-ImageViewer.ts, src/ImageViewer/ImageViewer.ts
Update inline documentation and readme
Update inline documentation and readme
N/A
=> Rd 1195 docs for cx

CHANGELOG.md, README.md
To update `next` branch against `main`
Merges `next` into `main`
N/A
=> Merge `main` into `next`
